### ISSUE TITLE
Update api to get all users

### ISSUE THREAD

**Issue by townofdon** [chiedolabs/blog-app-in-many-stacks#32]
Backend: nodejs-rest

In order to get post excerpts for all posts in the home page, I need to also load in the author information. Since only the author id is contained in each post object, I need to load all of the authors (i.e. users) in order to display the author's name, etc.

@chiedo let me know if this thinking is going down the wrong path.

**Comment by chiedo** [comment]
That sounds like the right path to me!
...but not worth it for this.

For now just query each user's endpoint.

In the future we could create a custom endpoint for getting multiple authors at once but not worth it since this isn't an actual app anyone will be using haha

If you really want a get all users endpoint though, go for it. I'm pretty indifferent

**Comment by townofdon** [comment]
Sounds good, I figured that making one api call would be more time-efficient so I went that route. :)
